export const SEND_CODE = '/users/send-confirmation-code'
export const CONFIRM_CODE = '/users/check-confirmation-code'
export const SET_PASSWORD = '/users/set-password'
export const SIGN_UP = '/users/sign-up'
export const SET_NAME = '/users/set-name'
