# Generated by Django 4.2.5 on 2023-09-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='verification_code',
        ),
    ]
