# Generated by Django 5.0 on 2023-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_country_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Region',
        ),
    ]
