# Generated by Django 5.0 on 2023-12-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('match', 'Juftlik topish'), ('friendship', "Do'st ortirish"), ('long_term_dating', 'Uzoq muddatli tanishuv'), ('short_term_dating', 'Qisqa muddatli tanishuv')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
