# Generated by Django 4.2.4 on 2023-09-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_otp_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
