# Generated by Django 5.0 on 2023-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
