# Generated by Django 5.0 on 2024-01-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high_school', "O'rta maxsus"), ('bachelors_degree', 'Bakalavr'), ('masters_degree', 'Magistratura'), ('doctorate', 'Doktorantura'), ('other', 'Boshqasi')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.profile')),
            ],
        ),
    ]
