# Generated by Django 5.0 on 2024-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', "O'rta maxsus"), ('bachelors_degree', 'Bakalavr'), ('masters_degree', 'Magistratura'), ('doctorate', 'Doktorantura'), ('other', 'Boshqasi')], max_length=20, null=True),
        ),
    ]
