# Generated by Django 5.0 on 2024-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_company',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_school',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqasi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('match', 'Juftlik topish'), ('friendship', "Do'st ortirish"), ('long_term_dating', 'Uzoq muddatli tanishuv'), ('short_term_dating', 'Qisqa muddatli tanishuv')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
