# Generated by Django 5.0 on 2024-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_job_company_profile_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', "Yolg'iz"), ('married', 'Uylangan'), ('divorced', 'Ajrashgan'), ('widowed', 'Beva'), ('engaged', 'Unashtirilgan'), ('relationship', 'Munosabatda'), ('other', 'Boshqasi')], max_length=20, null=True),
        ),
    ]
