# Generated by Django 5.0 on 2024-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='income_level',
            field=models.CharField(blank=True, choices=[('low', 'Past daromad'), ('moderate', "O'rtacha daromad"), ('above_moderate', "O'rtacha daromaddan yuqori"), ('high', 'Yuqori daromad'), ('very_high', 'Juda yuqori daromad')], max_length=20, null=True),
        ),
    ]
