# Generated by Django 5.0 on 2024-01-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_income_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqasi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('match', 'Juftlik topish'), ('friendship', "Do'st ortirish"), ('long_term_dating', 'Uzoq muddatli tanishuv'), ('short_term_dating', 'Qisqa muddatli tanishuv')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
