# Generated by Django 5.0 on 2024-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profileimage_button_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='button_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
