# Generated by Django 5.0 on 2024-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_profile_online_user_last_seen_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
