# Generated by Django 5.0 on 2024-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
