# Generated by Django 5.0 on 2024-05-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
