# Generated by Django 5.0 on 2024-05-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_like_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_dislike', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_dislike', to='users.profile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
