# Generated by Django 5.0 on 2024-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_like_is_active_dislike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
