# Generated by Django 5.0 on 2024-06-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('sender', 'receiver')},
        ),
    ]
