# Generated by Django 5.0 on 2024-06-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_device_token_remove_device_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
