# Generated by Django 5.0 on 2024-06-25 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_device_profile_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='profile',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
