# Generated by Django 5.0 on 2024-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_user_last_seen_remove_user_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='998'),
        ),
    ]
