# Generated by Django 5.0 on 2024-07-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='country_code',
            field=models.CharField(default='998'),
        ),
    ]
