# Generated by Django 5.0 on 2024-07-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_user_alter_room_participants'),
        ('users', '0047_confirmationcode_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='like',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
