# Generated by Django 5.0 on 2024-07-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('sender', 'receiver')},
        ),
    ]
