# Generated by Django 5.0 on 2024-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profileimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
