# Generated by Django 5.0 on 2024-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
